version: '3'
services:
  # nginx:
  #   image: nginx:mainline-alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/temp.html:/temp.html
  #   depends_on:
  #     - ruby_api
  #     - node_api
  #   networks:
  #     - app-network
  ruby_api:
    build:
      context: .
      dockerfile: ./ruby-api/Dockerfile
    container_name: ruby_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    # networks:
    #   - app-network

  node_api:
    build:
      context: .
      dockerfile: ./node-api/Dockerfile
    container_name: node_api
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    # networks:
    #   - app-network
# networks:
#   app-network:
#     driver: bridge