version: '3'
services:
  ruby_api:
    build:
      context: .
      dockerfile: ./ruby-api/Dockerfile
    container_name: ruby_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./.env
  node_api:
    build:
      context: .
      dockerfile: ./node-api/Dockerfile
    container_name: node_api
    restart: unless-stopped
    ports:
      - "3002:3002"
    env_file:
      - ./.env
