version: '3'
services:
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "3333:3333"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/temp.html:/temp.html
    depends_on:
      - ruby_api
      - node_api
    networks:
      - app-network
  ruby_api:
    build:
      context: .
      dockerfile: Dockerfile.ruby
    container_name: ruby_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    # env_file:
    #   - ./.env
      environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_PORT=${NODE_PORT}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY}
      - RPC=${RPC}
      - HELIUS_API_KEY=${HELIUS_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - CLOUDINARY_NFT_FOLDER=${CLOUDINARY_NFT_FOLDER}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network
  node_api:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_api
    restart: unless-stopped
    ports:
      - "3002:3002"
    # env_file:
    #   - ./.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_PORT=${NODE_PORT}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY}
      - RPC=${RPC}
      - HELIUS_API_KEY=${HELIUS_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - CLOUDINARY_NFT_FOLDER=${CLOUDINARY_NFT_FOLDER}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - SECRET_KEY=${SECRET_KEY}

    networks:
      - app-network
networks:
  app-network:
    driver: bridge